name: Issues handle
on: [issues, workflow_dispatch]
jobs:
    output-info:
        runs-on: ubuntu-latest
        steps:
            - name: Output the event details
              run: echo "${{ toJSON(github.event) }}"